### ISSUE TITLE
functions referring to window properties refer to the static ofPtr<ofAppBaseWindow> window instead of the NSWindow

### ISSUE THREAD

**Issue by pkmital** [whg/ofxNSWindower#1]
This breaks a lot of graphics stuff which need the window's size such as ofViewport (called by ofFbo, ofTexture, etc...)

**Comment by whg** [comment]
As far as I could see, there was no way to fix this without modifying the oF core. I have added a small patch that can be applied to oF to fix the issue. I haven't tested it a great deal but ofFbo seems to work now. Along with these changes normal oF getters (e.g. ofGetWidth()) work now.

**Comment by pkmital** [comment]
awesome will! thanks for that. i am having problems compiling it now though. i had to add the function declarations for the new functions you added to the ofxnswindowapp header.  the only remaining compile error is there is no defintion for: "ofSetAppWindow":

../../../addons/ofxNSWindower/src/ofxNSWindower.mm:61:2: error: use of undeclared identifier 'ofSetAppWindow'
        ofSetAppWindow(windows[name]);
        ^
1 error generated.

../../../addons/ofxNSWindower/src/OpenGLView.mm:232:2: error: use of undeclared identifier 'ofSetAppWindow'
        ofSetAppWindow(ofxNSWindower::instance()->getWindowPtr(windowApp->getParent()->getWindowTitle()));
        ^
1 error generated.

Any ideas? And thanks so much!

**Comment by pkmital** [comment]
oh dur sorry just now reading your note saying to add this to the core:

void ofSetAppWindow(ofPtr<ofAppBaseWindow> windowPtr) { window = windowPtr; }

thanks will!
