### ISSUE TITLE
ofxNSWindowApp::setWindowSize broken and ofxnswindowapp.h header declarations missing

### ISSUE THREAD

**Issue by pkmital** [whg/ofxNSWindower#2]
Sorry I'd submit a pull request if I knew how to do it.  Basically ofxNSWindowApp.mm needs this for lines 51-53:

void ofxNSWindowApp::setWindowSize(int w, int h) {
    parent->setWindowShape(w, h);
}

and ofxNSWindowApp.h needs these declarations:

```
void setWindowTitle(string title);    
ofPoint getWindowPosition();    
ofPoint getWindowSize();    
int getWidth();    
int getHeight();    
ofRectangle getFrame();    
float getFrameRate();    
void setFrameRate(float fr);    
int getFrameNum();    
float getRealFrameRate();    
void setWindowSize(int w, int h);    
void setWindowPosition(int x, int y);
```

**Comment by whg** [comment]
For setting and getting window properties, use normal oF functions like ofSetWindowShape(), ofGetHeight(), etc.  

ofxNSWindowApp shouldn't have an implementation file anymore, I had forgotten to remove it from the working tree. This should be fixed now.

**Comment by pkmital** [comment]
ok makes sense thanks will!
