### ISSUE TITLE
testApp is never released

### ISSUE THREAD

**Issue by pkmital** [whg/ofxNSWindower#3]
just add an ivar to the interface of AppDelegate and in applicationWillTerminate, delete this ivar. e.g.:

in AppDelegate.h:
# include "testApp.h"
# include "ofxNSWindower.h"
# import <Cocoa/Cocoa.h>

@interface AppDelegate : NSObject <NSApplicationDelegate> {
    testApp *appPtr;
}

@end

and in AppDelegate.mm:
# import "AppDelegate.h"

@implementation AppDelegate
- (void) applicationDidFinishLaunching: (NSNotification*) notification {
  
  appPtr = new testApp();
  ofxNSWindower::instance()->addWindow(appPtr, "saver", NSTitledWindowMask, 0);

}
- (void) applicationWillTerminate: (NSNotification*) notification {
  
  delete appPtr;
  ofxNSWindower::destroy();
  }

@end

**Comment by pkmital** [comment]
Sorry it's not really to do with your library but thought the examples might want it

**Comment by whg** [comment]
This has been fixed, the app is explicitly deleted inside ofxNSWindower. I think this makes better sense, as pointers to apps can be retrieved with ofxNSWinower::getAppPtr() and then you don't need to declare any ivars.

**Comment by pkmital** [comment]
awesome
